@php
    $id = 'index';
    $title = 'I Am A Freelancer From Sri Lanka';
    $description = 'I am a back-end engineer, system administrator, and website security expert based in Sri Lanka. With years of experience, I specialize in building and managi...';
    $keywords = 'enindu, enindu alahapperuma, freelancer, software engineer, sri lanka, back-end engineer, system administrator, website security expert';
@endphp

@extends('components.layouts.base')
@section('content')
    <div class="card rounded-5 p-3">
        <div class="card-body">
            <div class="d-flex flex-column gap-3">
                <h1 class="mb-0">I Am A Freelancer From Sri Lanka</h1>
                <p class="mb-0">I am a back-end engineer, system administrator, and website security expert based in Sri Lanka. With years of experience, I specialize in building and managing reliable, secure, and efficient systems. Below, you can explore more about my professional journey, expertise, and the services I offer.</p>
            </div>
        </div>
    </div>
    <div class="card rounded-5 p-3">
        <div class="card-body">
            <div class="d-flex flex-column gap-3">
                <h2 class="mb-0">About Me</h2>
                <h3 class="mb-0">Brief Introduction</h3>
                <p class="mb-0">I'm Enindu Alahapperuma, a freelancing software engineer from Sri Lanka. With over 7 years of experience in back-end engineering, I specialize in back-end development, system administration, and website security. My journey started with a passion for Linux and open-source software, which naturally led me into system administration. Over time, I transitioned into back-end development, where I now focus on creating and managing reliable, secure, and efficient systems.</p>
                <p class="mb-0">My journey into back-end engineering and system administration began with Ubuntu 5.04, almost a decade ago. The moment I installed it, I knew Linux was the right fit for me. Today, I continue to use a Linux distribution, specifically Arch Linux. After my initial experience with Ubuntu 5.04, I went through a phase of distro hopping, where I explored almost every major Linux distribution, including Debian, Fedora, Mint, openSUSE, Manjaro, Zorin, elementary, NixOS, Kali, Gentoo, and some lesser-known ones like Puppy, Tiny Core, CrunchBang, Void, ArchBang, and Damn Small. I even tried BSD distributions like OpenBSD, GhostBSD, and FreeBSD. Despite using so many UNIX-like distributions, I ultimately settled on Arch Linux, which remains my preferred choice.</p>
                <p class="mb-0">My experience as a distro hopper has given me a deep understanding of various Linux communities, philosophies, build systems, GUIs, CLIs, kernels, and tools. This knowledge has strengthened my abilities as a system administrator and security expert. With this expertise, I transitioned into the web development field and eventually became a back-end engineer. Today, my professional identity is defined by my specialization in network programming, protocols, encryption, databases, servers, cloud computing, and website security.</p>
                <p class="mb-0">While I consider myself a web developer, I am not a full-stack developer or a DevOps engineer. I believe the concept of a full-stack developer is flawed, especially in the web development field. A full-stack developer is expected to be skilled in both front-end and back-end development, but this can lead to a lack of depth in either area. Similarly, DevOps is a unique discipline that combines development and operations practices to enhance the software development lifecycle. It focuses more on the application lifecycle rather than server management.</p>
                <h3 class="mb-0">Back-End Engineering</h3>
                <p class="mb-0">Before I became a professional back-end engineer, I started my career as a web developer. I've always been a curious person, constantly questioning and analyzing the tasks I take on, and this curiosity drove me deeper into the world of web development, much like my journey with Linux. During my time as a web developer, I experimented with various frameworks, tools, and CMSs. I even created my own CSS frameworks, PHP frameworks, and tools to help with my development. This hands-on experience allowed me to gain significant knowledge quickly, which ultimately led me to pursue back-end development as my career path.</p>
                <p class="mb-0">Like many others, I didn't choose back-end development just for financial reasons. My true passion lies in understanding how systems work. I've always been more fascinated by the intricacies of server-side operations than by front-end development. Even though I have a lot of experience, my knowledge of front-end frameworks like React or Vue is minimal. My focus is on how web browsers communicate with servers, how servers process those requests, and how responses are sent back to the browsers. This is where my genuine interest lies.</p>
                <p class="mb-0">As a back-end engineer, I primarily work with Apache, nginx, and PHP as my enterprise-level stack. I often integrate cloud computing technologies to optimize the applications I build. Even though my main focus is back-end engineering, I still work as a freelance web developer. For building robust websites, I rely exclusively on Laravel as my framework of choice. I prefer not to use CMS platforms like WordPress or Drupal because they tend to be bulkier and don't always follow certain standards. While Laravel may not be the lightest framework, it offers a great balance of performance and adherence to best practices, which I find crucial for my projects.</p>
                <p class="mb-0">Go is my language of choice for network programming. Unlike PHP, which runs within Apache or nginx, Go operates at a lower level. I also use Go to create everyday CLI programs, which you can explore on my GitHub profile. Go is a simple yet powerful language, especially suited for network programming. It makes manipulating protocols easy and comes with a comprehensive standard library that includes I/O tools, operating system tools, database tools, encoding tools, hashing tools, and both low-level networking and higher-level HTTP tools. Its concurrency model makes Go ideal for back-end engineering, particularly in performance-critical applications. Additionally, Go is a strictly typed, procedural language, and its straightforward syntax and features make it my top choice for many projects.</p>
                <p class="mb-0">In addition to PHP and Go, I also have hands-on experience with Node.js. While JavaScript isn't my preferred language, I appreciate Node.js for its non-blocking nature, which makes it a great choice for I/O programming. This feature allows Node.js to efficiently handle I/O operations, which is why I turn to it for such tasks.</p>
                <h3 class="mb-0">System Administration</h3>
                <p class="mb-0">Even though my primary profession is back-end engineering, my true passion lies in system administration, which was the foundation of my career. I am a skilled Linux system administrator with extensive experience in various build systems and tools. Thanks to my back-end expertise, I work with LAMP (Linux, Apache, MySQL/MariaDB, PHP) stacks daily. In addition, I manage operating systems, networks, firewalls, and servers, overseeing their installation, maintenance, monitoring, and troubleshooting.</p>
                <p class="mb-0">My expertise primarily lies in Linux, covering a vast range of knowledge. Although I have hands-on experience with BSD and Windows, I don't consider myself an expert in those systems. I've worked with various Linux distributions like Debian and NixOS, as well as different init systems used in Arch Linux and Void. My experience also includes diverse toolsets, such as Ubuntu and Kali, and environments ranging from GUIs like KDE and GNOME to CLIs. I'm proficient with different package managers, including pacman and dnf. This experience has given me expertise in operating system management, including day-to-day tasks, monitoring, analysis, and user management. Additionally, I manage SSH, VNC, and RDP servers.</p>
                <p class="mb-0">Throughout my career, I've managed hundreds of HTTP servers and mail servers like SMTP, IMAP, and POP3, which has helped refine my skills as a system administrator in the web hosting domain. Managing HTTP servers requires a solid understanding of DNS, TLS, proxies, cron jobs, version control, and log analysis. My expertise in web development, back-end development, and network programming has made me a true expert in system administration within this field.</p>
                <p class="mb-0">In addition to managing HTTP and mail servers, I also create and maintain low-level TCP, UDP, and UNIX servers through network programming. My expertise as a system administrator spans various types of servers, and I enjoy exploring low-level networking concepts in my free time. I have a deep understanding of how these protocols work and how clients should interact with them. Additionally, I have some knowledge of banking servers, including their protocols and standards.</p>
                <p class="mb-0">In addition to back-end engineering and general system administration, I also have expertise in cloud computing. Early in my career, I utilized cloud services to enhance my web applications. As I gained more experience and leveraged my system administration skills, I became proficient in cloud computing system administration. I primarily work with Amazon Web Services (AWS) due to its stability and reliability, but I also have hands-on experience with DigitalOcean and Google Cloud. Today, I offer comprehensive system administration services on any cloud platform. However, it's important to clarify that my services are distinct from DevOps, as I focus solely on system administration rather than DevOps practices.</p>
                <h3 class="mb-0">Website Security</h3>
                <p class="mb-0">Over time, my experience in web development, back-end engineering, and system administration has refined my skills as a website security expert. I am responsible for remaining vigilant against potential threats while working in these areas, ensuring security across every stage of development and system management. This constant vigilance has helped me become proficient in website security. Using my broad knowledge of systems and practices, I manage security at the operating system, network, and application levels.</p>
                <p class="mb-0">To ensure robust security, I follow practices such as patching operating system vulnerabilities, consistently updating to the latest versions, adhering to best practices and standards, and managing TLS certificates. I also use tools like port scanning, network scanning, and website scanning tools to check for vulnerabilities. As a security expert, I understand that no system is ever 100% secure—every system has potential vulnerabilities that may not be immediately visible. It's important to stay vigilant and proactive. With my extensive experience, I always strive to maintain the highest level of security.</p>
                <h3 class="mb-0">Freelancing</h3>
                <p class="mb-0">With all the experience I've shared, I now offer my services to the public as a freelancer in web development and system administration. If you think I can assist with your project or have the expertise to meet your needs, please feel free to contact me via <a class="text-decoration-none" href="mailto:{{ env('APP_EMAIL') }}">{{ env('APP_EMAIL') }}</a>. For more information, including pricing plans and detailed service descriptions, you can visit the <a class="text-decoration-none" href="{{ route('services.index') }}">Services</a> page. Don't forget to check it out!</p>
            </div>
        </div>
    </div>
    <div class="card rounded-5 p-3">
        <div class="card-body">
            <div class="d-flex flex-column gap-3">
                <h2 class="mb-0">About Website</h2>
                <h3 class="mb-0">Changelog</h3>
                <p class="mb-0">This is the 4th version of my website. The first two versions were built using a custom static site generator written in Go. For various reasons, I migrated to Laravel in the 3rd version. In this 4th version, I've updated the Laravel framework to its latest version and made several front-end improvements to enhance the user experience.</p>
                <p class="mb-0">In this version of the website, I continue to use a technology stack that includes plain HTML, Halfmoon as my CSS framework, and Laravel as my PHP framework. Although the website doesn't require a database for its operations, Laravel uses SQLite for its database needs. The website is hosted on an AWS EC2 instance and served through an Apache HTTP server. Cloudflare is integrated as a reverse proxy server to enhance both security and performance. DNS management from the origin to the proxy is handled through AWS Route 53, while proxy to client DNS management is handled via Cloudflare.</p>
                <h3 class="mb-0">Contribute</h3>
                <p class="mb-0">The source code for this website is available on my GitHub profile under the MIT license. You are free to distribute and modify the source code as outlined in the license. Visit <a class="text-decoration-none" href="https://github.com/enindu/enindu-alahapperuma" target="_blank">this link</a> to view the source code. If you encounter any issues or have suggestions for improvements, feel free to open an issue or submit a pull request. Your contributions are greatly appreciated and help make this project better for everyone.</p>
            </div>
        </div>
    </div>
@endsection
